apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    deployment: mariadb
spec:
  selector:
    matchLabels:
      pod: mariadb
  template:
    metadata:
      labels:
        pod: mariadb
    spec:
      containers:
        - name: mariadb-container
          image: mariadb:10.3.28-focal
          ports:
            - containerPort: 3306
          env:
            - { name: MYSQL_ROOT_PASSWORD,    value: something-random     }
            - { name: MYSQL_DATABASE,         value: my-created-database  }
            - { name: MYSQL_USER,             value: mysql-user           }
            - { name: MYSQL_PASSWORD,         value: mysql-password       }
          volumeMounts:
            - name: mariadb-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-volume
          persistentVolumeClaim:
            claimName: mariadb-volume-claim
