apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    pod: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis-replica
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    pod: redis-replica
