apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    pod: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis-replica-service
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    pod: redis-replica
