apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-web-deployment
  labels:
    deployment: mage-web
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: mage-web
  template:
    metadata:
      labels:
        pod: mage-web
    spec:
      containers:
        - name: mage-web-container
          image: domdambrogia/misc:2021-02-26-php-src-85ab
          ports:
            - name: mage-web-ports
              containerPort: 8080
              protocol: TCP
          env:
            - { name: AMQP_HOST,        value: 'rmq-service'      }
            - { name: AMQP_PORT,        value: '5672'             }
            - { name: AMQP_USER,        value: 'guest'            }
            - { name: AMQP_PASSWORD,    value: 'guest'            }
            - { name: MYSQL_HOST,       value: 'mysql-service'    }
            - { name: MYSQL_USER,       value: 'mysql-user'       }
            - { name: MYSQL_PASSWORD,   value: 'mysql-pw'         }
            - { name: REDIS_HOST,       value: 'redis-service'    }
            - { name: REDIS_PORT,       value: '6379'             }
