apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
  labels:
    deployment: rmq
spec:
  selector:
    matchLabels:
      pod: rmq
  template:
    metadata:
      labels:
        pod: rmq
    spec:
      containers:
        - name: rmq-container
          image: rabbitmq:3.7.6-management
          ports:
            - containerPort: 15672
            - containerPort: 5672
      volumes:
        - name: rmq-volume
          persistentVolumeClaim:
            claimName: rmq-volume-claim
