apiVersion: v1
kind: Service
metadata:
  name: rmq-service
spec:
  type: ClusterIP
  selector:
    pod: rmq
  ports:
    - name: rmq-managment-port
      port: 15672
    - name: rmq-service-port
      port: 5672
